### ISSUE TITLE
フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yamakazugo** [yamakazugo/furima-29649#9]
#URL
https://furima-29649.herokuapp.com/
#Basic認証のIDとパスワード
kazugo/0634
#出品者用のメールアドレスとパスワード
sutaba@gmail.com / sutaba3150
#購入者用のメールアドレスとパスワード
coffee@gmail.com / coffee3150
#購入用カードの番号・期限・セキュリティコード
4242424242424242・3月25年・123

**Comment by mo1015** [comment]
山口さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**○入力に問題がある状態で出品ボタンが押されたら、出品ページに戻りエラーメッセージが表示されるようにしましょう**
→画像0枚で出品ボタンを押したとき、エラー画面に遷移してしまいます

修正でき次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by yamakazugo** [comment]
ご確認ありがとうございます。
「○入力に問題がある状態で出品ボタンが押されたら、出品ページに戻りエラーメッセージが表示されるようにしましょう」と
ご指摘して頂いた件修正させて頂きましたのでご確認の程、何卒よろしくお願い致します。

**Comment by mo1015** [comment]
再提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます:tada:
おめでとうございます！
**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
